### ISSUE TITLE
Beautify the Popup Modals in Frontend

### ISSUE THREAD

**Issue by RohanKaran** [RohanKaran/VaultSafe#5]
**Is your feature request related to a problem? Please describe.**
- Beautify the PasswordModal and NoteModal
- Make the borderradius to 0 of these modals
- Keep the colors similar to greyish theme

**Additional context**
- ```frontend/src/components/```

**Comment by DevTomilola-OS** [comment]
Kindly assign this to me.

**Comment by abhishekpatil4** [comment]
@RohanKaran Assign me this task, I'm a full-stack (MERN) developer

**Comment by RohanKaran** [comment]
Hi @abhishekpatil4 , this issue is assigned to @DevTomilola-OS . You may want to work on other open issues - https://github.com/RohanKaran/VaultSafe/issues

**Comment by DevTomilola-OS** [comment]
![Screenshot 2022-10-04 22 05 36](https://user-images.githubusercontent.com/114832204/193928641-fb835bce-f5be-4fcf-b5d8-1ed69593d186.png)

Helloa @RohanKaran I'm trying to run the project locally. The frontend works fine but the backend still giving me some issues, anytime i try to run python initial_data.py i keep getting these errors, how do i fix this and run the backend successfully.

**Comment by RohanKaran** [comment]
> ![Screenshot 2022-10-04 22 05 36](https://user-images.githubusercontent.com/114832204/193928641-fb835bce-f5be-4fcf-b5d8-1ed69593d186.png)
> 
> Helloa @RohanKaran I'm trying to run the project locally. The frontend works fine but the backend still giving me some issues, anytime i try to run python initial_data.py i keep getting these errors, how do i fix this and run the backend successfully.

I pushed some changes, just pull the recent changes to your forked repo. Basically sync your forked repo. If you face any difficulties, let me know.

**Comment by DevTomilola-OS** [comment]
Okay, thank you.

**Comment by RohanKaran** [comment]
closed by #10
