### ISSUE TITLE
Display a loading spinner on Log in button

### ISSUE THREAD

**Issue by RohanKaran** [RohanKaran/VaultSafe#7]
**Is your feature request related to a problem? Please describe.**
- Currently if a user clicks on Log in it does not show any loading status

**Describe the solution you'd like**
- Display a loading spinner on Log in (from react-bootstrap) between user click and server response period.
- Do not forget to hide/disable the spinner after you receive a response from the server.

**Additional context**
- ```frontend/src/pages/LoginPage.js:55```
- This won't be a straightforward react state update task as you might have to modify ```frontend/src/context/AuthContext.js``` and pass extra props in order to achieve this task.

**Comment by lejara** [comment]
Heyo!

May I take this on?

**Comment by RohanKaran** [comment]
Sure @lejara
